query PostContent($slug: String) {
	post(filter: { slug: { eq: $slug } }) {
		title
		slug
		date
		coverImage {
			...ImageFragment
		}
		content {
			...StructuredTextFragment
		}
		ogImage: coverImage {
			url(imgixParams: { fm: jpg, fit: crop, w: 2000, h: 1000 })
		}
		seo: _seoMetaTags {
			attributes
			content
			tag
		}
	}

	site: _site {
		favicon: faviconMetaTags {
			attributes
			content
			tag
		}
	}
}
